#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY . .
RUN mvn clean package -DskipTests

#
# Package stage
#
FROM openjdk:19
COPY --from=build /target/research.jar research.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","research.jar"]